# GitHub Pages Configuration
title: AgriNexus AI Documentation
description: >-
  Comprehensive documentation for the AgriNexus AI Agricultural Management Platform,
  covering user roles, permissions, and system features.

# GitHub Pages will use Jekyll by default
# Use the minimal theme for simplicity
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Navigation
navigation:
  - title: Home
    url: /
  - title: User Account Types
    url: /user-account-types/
  - title: Role Permissions
    url: /user-account-types/#permission-matrix
  - title: Security Features
    url: /user-account-types/#security-features

# Site metadata
author:
  name: AgriNexus AI Team
  email: docs@agrinexus.ai

# Social links
github_username: agrinexus-ai

# Google Analytics (uncomment and add your GA tracking ID)
# google_analytics: UA-XXXXXXXX-X

# SEO settings
lang: en_US
timezone: UTC

# Custom CSS
sass:
  sass_dir: _sass
  style: compressed