name: NodeJS with Vite

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Lint
      run: npm run lint --if-present

    - name: Build (Vite)
      run: npm run build

    - name: Start API server (background)
      run: |
        nohup npm run server >/dev/null 2>&1 &
        echo $! > server.pid
        sleep 2
        curl -f http://localhost:3001/healthz

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      env:
        CI: true
      run: npx playwright test

    - name: Stop API server
      if: always()
      run: |
        if [ -f server.pid ]; then kill $(cat server.pid) || true; fi
